# Generated by Django 3.1 on 2021-12-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0002_auto_20211211_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='orders.order'),
        ),
    ]
